stages:
- name: 单元测试
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: echo "golang unit test ..."
- name: 构建镜像并推送
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: vienfu/jenkins-demo:rancher
      pushRemote: true
      registry: 127.0.0.1:34667
- name: 结果说明
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: echo "success"
timeout: 60
notification: {}
